services:
  composer_manager.event_subscriber:
    class: Drupal\composer_manager\AutoloaderSubscriber
    arguments: ['@composer_manager.manager']
    tags:
      - { name: event_subscriber }

  composer_manager.filesystem:
    class: Drupal\composer_manager\Filesystem

  composer_manager.manager:
    class: Drupal\composer_manager\ComposerManager
    arguments: ['@config.factory', '@module_handler', '@composer_manager.filesystem']

  composer_manager.packages:
    class: Drupal\composer_manager\ComposerPackages
    arguments: ['@lock', '@module_handler', '@composer_manager.filesystem', '@composer_manager.manager']
